"""initial baseline

Revision ID: 9f02320c4da1
Revises: 
Create Date: 2026-03-31 10:32:53.956415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f02320c4da1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('icon_key', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_menus_id'), 'menus', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_menus_role'), 'menus', ['role'], unique=False, schema='core')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_projects_id'), 'projects', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_projects_owner'), 'projects', ['owner'], unique=False, schema='core')
    op.create_index(op.f('ix_core_projects_title'), 'projects', ['title'], unique=False, schema='core')
    op.create_table('solver_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solver_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('encrypted_api_key', sa.String(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_solver_settings_solver_id'), 'solver_settings', ['solver_id'], unique=True, schema='core')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_id'), 'users', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_username'), 'users', ['username'], unique=True, schema='core')
    op.create_table('problem_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(), nullable=True),
    sa.Column('math_model_type', sa.String(), nullable=True),
    sa.Column('decision_rules', sa.JSON(), nullable=True),
    sa.Column('supported_algorithms', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='domain'
    )
    op.create_index(op.f('ix_domain_problem_templates_id'), 'problem_templates', ['id'], unique=False, schema='domain')
    op.create_index(op.f('ix_domain_problem_templates_task_key'), 'problem_templates', ['task_key'], unique=True, schema='domain')
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='domain'
    )
    op.create_index(op.f('ix_domain_scenarios_id'), 'scenarios', ['id'], unique=False, schema='domain')
    op.create_index(op.f('ix_domain_scenarios_task_key'), 'scenarios', ['task_key'], unique=True, schema='domain')
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('card_json', sa.Text(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_chat_history_id'), 'chat_history', ['id'], unique=False, schema='chat')
    op.create_table('intent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('pipeline_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_intent_logs_id'), 'intent_logs', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_intent_logs_project_id'), 'intent_logs', ['project_id'], unique=False, schema='core')
    op.create_table('session_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('current_dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('current_model_version_id', sa.Integer(), nullable=True),
    sa.Column('current_run_id', sa.Integer(), nullable=True),
    sa.Column('file_uploaded', sa.Boolean(), nullable=True),
    sa.Column('analysis_completed', sa.Boolean(), nullable=True),
    sa.Column('math_model_confirmed', sa.Boolean(), nullable=True),
    sa.Column('pre_decision_done', sa.Boolean(), nullable=True),
    sa.Column('optimization_done', sa.Boolean(), nullable=True),
    sa.Column('uploaded_files', sa.Text(), nullable=True),
    sa.Column('csv_summary', sa.Text(), nullable=True),
    sa.Column('last_analysis_report', sa.Text(), nullable=True),
    sa.Column('math_model', sa.Text(), nullable=True),
    sa.Column('last_pre_decision_result', sa.Text(), nullable=True),
    sa.Column('last_optimization_result', sa.Text(), nullable=True),
    sa.Column('data_facts', sa.Text(), nullable=True),
    sa.Column('solver_selected', sa.String(), nullable=True),
    sa.Column('pending_param_inputs', sa.Text(), nullable=True),
    sa.Column('clarification_answers', sa.Text(), nullable=True),
    sa.Column('pending_clarifications', sa.Text(), nullable=True),
    sa.Column('clarification_done', sa.Boolean(), nullable=True),
    sa.Column('problem_defined', sa.Boolean(), nullable=True),
    sa.Column('problem_definition', sa.Text(), nullable=True),
    sa.Column('confirmed_problem', sa.Text(), nullable=True),
    sa.Column('data_normalized', sa.Boolean(), nullable=True),
    sa.Column('normalization_mapping', sa.Text(), nullable=True),
    sa.Column('normalized_data_summary', sa.Text(), nullable=True),
    sa.Column('structural_normalization_done', sa.Boolean(), nullable=True),
    sa.Column('phase1_summary', sa.Text(), nullable=True),
    sa.Column('constraints_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_constraints', sa.Text(), nullable=True),
    sa.Column('objective_changing', sa.Boolean(), nullable=True),
    sa.Column('pending_objective', sa.Text(), nullable=True),
    sa.Column('pending_extra_instructions', sa.String(), nullable=True),
    sa.Column('pending_category_change', sa.Text(), nullable=True),
    sa.Column('detected_domain', sa.String(), nullable=True),
    sa.Column('domain_confidence', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_session_states_id'), 'session_states', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_session_states_project_id'), 'session_states', ['project_id'], unique=True, schema='core')
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('domain_type', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('file_list', sa.Text(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_index(op.f('ix_data_dataset_versions_id'), 'dataset_versions', ['id'], unique=False, schema='data')
    op.create_index(op.f('ix_data_dataset_versions_project_id'), 'dataset_versions', ['project_id'], unique=False, schema='data')
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('backend', sa.String(), nullable=True),
    sa.Column('solver_id', sa.String(), nullable=True),
    sa.Column('solver_name', sa.String(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('compare_group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='job'
    )
    op.create_index(op.f('ix_job_jobs_id'), 'jobs', ['id'], unique=False, schema='job')
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('domain_type', sa.String(), nullable=True),
    sa.Column('objective_type', sa.String(), nullable=True),
    sa.Column('objective_summary', sa.String(), nullable=True),
    sa.Column('model_json', sa.Text(), nullable=True),
    sa.Column('variable_count', sa.Integer(), nullable=True),
    sa.Column('constraint_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['data.dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='model'
    )
    op.create_index(op.f('ix_model_model_versions_id'), 'model_versions', ['id'], unique=False, schema='model')
    op.create_index(op.f('ix_model_model_versions_project_id'), 'model_versions', ['project_id'], unique=False, schema='model')
    op.create_table('run_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('domain_type', sa.String(), nullable=True),
    sa.Column('solver_id', sa.String(), nullable=False),
    sa.Column('solver_name', sa.String(), nullable=True),
    sa.Column('solver_params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('compile_time_sec', sa.Float(), nullable=True),
    sa.Column('execute_time_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model.model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='job'
    )
    op.create_index(op.f('ix_job_run_results_id'), 'run_results', ['id'], unique=False, schema='job')
    op.create_index(op.f('ix_job_run_results_project_id'), 'run_results', ['project_id'], unique=False, schema='job')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_run_results_project_id'), table_name='run_results', schema='job')
    op.drop_index(op.f('ix_job_run_results_id'), table_name='run_results', schema='job')
    op.drop_table('run_results', schema='job')
    op.drop_index(op.f('ix_model_model_versions_project_id'), table_name='model_versions', schema='model')
    op.drop_index(op.f('ix_model_model_versions_id'), table_name='model_versions', schema='model')
    op.drop_table('model_versions', schema='model')
    op.drop_index(op.f('ix_job_jobs_id'), table_name='jobs', schema='job')
    op.drop_table('jobs', schema='job')
    op.drop_index(op.f('ix_data_dataset_versions_project_id'), table_name='dataset_versions', schema='data')
    op.drop_index(op.f('ix_data_dataset_versions_id'), table_name='dataset_versions', schema='data')
    op.drop_table('dataset_versions', schema='data')
    op.drop_index(op.f('ix_core_session_states_project_id'), table_name='session_states', schema='core')
    op.drop_index(op.f('ix_core_session_states_id'), table_name='session_states', schema='core')
    op.drop_table('session_states', schema='core')
    op.drop_index(op.f('ix_core_intent_logs_project_id'), table_name='intent_logs', schema='core')
    op.drop_index(op.f('ix_core_intent_logs_id'), table_name='intent_logs', schema='core')
    op.drop_table('intent_logs', schema='core')
    op.drop_index(op.f('ix_chat_chat_history_id'), table_name='chat_history', schema='chat')
    op.drop_table('chat_history', schema='chat')
    op.drop_index(op.f('ix_domain_scenarios_task_key'), table_name='scenarios', schema='domain')
    op.drop_index(op.f('ix_domain_scenarios_id'), table_name='scenarios', schema='domain')
    op.drop_table('scenarios', schema='domain')
    op.drop_index(op.f('ix_domain_problem_templates_task_key'), table_name='problem_templates', schema='domain')
    op.drop_index(op.f('ix_domain_problem_templates_id'), table_name='problem_templates', schema='domain')
    op.drop_table('problem_templates', schema='domain')
    op.drop_index(op.f('ix_core_users_username'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_id'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index(op.f('ix_core_solver_settings_solver_id'), table_name='solver_settings', schema='core')
    op.drop_table('solver_settings', schema='core')
    op.drop_index(op.f('ix_core_projects_title'), table_name='projects', schema='core')
    op.drop_index(op.f('ix_core_projects_owner'), table_name='projects', schema='core')
    op.drop_index(op.f('ix_core_projects_id'), table_name='projects', schema='core')
    op.drop_table('projects', schema='core')
    op.drop_index(op.f('ix_core_menus_role'), table_name='menus', schema='core')
    op.drop_index(op.f('ix_core_menus_id'), table_name='menus', schema='core')
    op.drop_table('menus', schema='core')
    # ### end Alembic commands ###
